      window.rdoEvents = {
        general: [
          ['00:00','Cold Dead Hands'],
          ['00:45','Railroad Baron'],			
          ['01:30','Wild Animal Kills'],
          ['02:15','Fool’s Gold'],			
          ['03:00','Random *'],
          ['03:45','Wildlife Photographer'],			
          ['04:30','King of the Castle'],
          ['05:15','Fishing Challenge'],			
          ['06:00','Dispatch Rider'],
          ['06:45','Random *'],			
          ['07:30','Wildlife Photographer'],
          ['08:15','Railroad Baron'],			
          ['09:00','Master Archer'],
          ['09:45','Wildlife Photographer'],			
          ['10:30','Fishing Challenge'],
          ['11:15','King of the Castle'],			
          ['12:00','Cold Dead Hands'],
          ['12:45','Railroad Baron'],			
          ['13:30','Wild Animal Kills'],
          ['14:15','Fool’s Gold'],			
          ['15:00','Random *'],
          ['15:45','Wildlife Photographer'],			
          ['16:30','King of the Castle'],
          ['17:15','Fishing Challenge'],			
          ['18:00','Dispatch Rider'],
          ['18:45','Random *'],			
          ['19:30','Wildlife Photographer'],
          ['20:15','Railroad Baron'],			
          ['21:00','Master Archer'],
          ['21:45','Wildlife Photographer'],			
          ['22:30','Fishing Challenge'],
          ['23:15','King of the Castle']
        ],
        role: [
          ['00:22','Protect Legendary Animal (Naturalist)'], 
          ['01:52','Day of Reckoning (Bounty Hunter)'],			
          ['03:22','Wild Animal Tagging (Naturalist)'],
          ['04:52','Manhunt (Bounty Hunter)'],			
          ['06:22','Trade Route (Trader)'],
          ['07:52','Condor Egg (Collector)'],			
          ['09:22','Day of Reckoning (Bounty Hunter)'],
          ['10:52','Protect Legendary Animal (Naturalist)'],			
          ['12:22','Manhunt (Bounty Hunter)'],
          ['13:52','Salvage (Collector)'],			
          ['15:22','Day of Reckoning (Bounty Hunter)'],
          ['16:52','Wild Animal Tagging (Naturalist)'],			
          ['18:22','Manhunt (Bounty Hunter)'],
          ['19:52','Trade Route (Trader)'],			
          ['21:22','Condor Egg (Collector)'],
          ['22:52','Day of Reckoning (Bounty Hunter)']
        ]
      };
